ARG REPO_LOWER
ARG VERSION

FROM ghcr.io/${REPO_LOWER}/temp:${VERSION} AS temp
FROM ghcr.io/${REPO_LOWER}/backend:${VERSION}

WORKDIR /app
COPY --from=temp /build/dist /app/web

EXPOSE 3002
CMD ["./sun-panel"]
