ARG REPO_LOWER
ARG VERSION

FROM ghcr.io/${REPO_LOWER}/temp:${VERSION} AS builder
WORKDIR /build

FROM nginx:alpine

# Setup timezone. (Optional)
ENV TZ=Asia/Shanghai

RUN apk add --no-cache bash curl tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo "$TZ" > /etc/timezone

COPY --from=builder /build/dist /usr/share/nginx/html
COPY distribution/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
