# build binary
FROM golang:1.24-alpine as builder
ARG VERSION

WORKDIR /build
COPY ./service .

# gcc, musl-dev are required for go-sqlite3
RUN apk add bash curl gcc git musl-dev && \
    go env -w GO111MODULE=on && \
    export PATH=$PATH:/go/bin && \
    export CGO_ENABLED=1 && \
    go build -o sun-panel --ldflags="-X sun-panel/global.RUNCODE=release -X sun-panel/lib/cmn.Version=${VERSION}" main.go

# final image
FROM alpine
WORKDIR /app
COPY --from=builder /build/sun-panel /app/sun-panel
COPY service/conf /app/conf
COPY service/lang /app/lang

EXPOSE 3002
RUN chmod +x ./sun-panel
CMD ./sun-panel