ARG REPO_LOWER
ARG VERSION

FROM ghcr.io/${REPO_LOWER}/temp:${VERSION} AS builder
WORKDIR /build

FROM nginx:alpine
COPY --from=builder /build/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
