services:
  yin-panel:
    image: ghcr.io/phantommaa/yin-panel/monolith:latest
    container_name: yin-panel
    volumes:
      - ./conf.yaml:/app/conf.yaml
      - ./uploads:/app/uploads
      - ./database:/app/database
    ports:
      - 3002:3002
