apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "yin-panel.fullname" . }}
  labels:
    {{- include "yin-panel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yin-panel.selectorLabels" . | nindent 4 }}
