FROM node:18.20.6-alpine

WORKDIR /build/frontend

# First copy only package files to leverage Docker cache
COPY frontend/.env frontend/package.json frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Then copy the rest of the application
COPY frontend .

# Build the application
RUN npm run build
