# build binary
FROM golang:1.24-alpine as builder
ARG VERSION

WORKDIR /build
COPY backend .

# gcc, musl-dev are required for go-sqlite3
RUN apk add --no-cache bash curl gcc git musl-dev && \
    go env -w GO111MODULE=on && \
    export PATH=$PATH:/go/bin && \
    export CGO_ENABLED=1 && \
    go build -o sun-panel --ldflags="-X sun-panel/global.RUNCODE=release -X sun-panel/global.VERSION=${VERSION}" main.go

# final image
FROM alpine
WORKDIR /app

# Setup timezone. (Optional)
ENV TZ=Asia/Shanghai

RUN apk add --no-cache bash curl tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo "$TZ" > /etc/timezone

COPY --from=builder /build/sun-panel /app/sun-panel
COPY backend/lang /app/lang
COPY backend/conf.ini /app/conf.ini

EXPOSE 3002
RUN chmod +x ./sun-panel
CMD ./sun-panel
