FROM alpine:3.19

WORKDIR /app

ARG VERSION
ENV TZ=Asia/Shanghai

RUN apk add --no-cache bash curl tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo "$TZ" > /etc/timezone && \
    mkdir -p /app/lang

COPY build-output/yin-panel /app/yin-panel
COPY backend/web /app/web
COPY backend/lang /app/lang
COPY backend/conf.yaml /app/conf.yaml

EXPOSE 3002
RUN chmod +x /app/yin-panel
CMD ["/app/yin-panel"]
